nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - '%env(CORS_ALLOW_ORIGIN)%'
        allow_methods:
            - GET
            - OPTIONS
            - POST
            - PUT
            - PATCH
            - DELETE
        allow_headers:
            - Content-Type
            - Authorization
        expose_headers:
            - Link
        max_age: 3600
        allow_credentials: false
        allow_private_network: false
        hosts: {  }
        forced_allow_origin_value: null
        skip_same_as_origin: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600